FROM python:latest
RUN pip install fastapi uvicorn httpie requests httpx flask pytest python-jose[cryptography] passlib python-multipart hypothesis schemathesis faker plotly kaleido pandas country_converter
WORKDIR /
