version: '3'

services:
  php:
    container_name: c-sf5-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile      
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    ports:
    - 5001:80
  python:
    container_name: c-sf5-python
    command: python /server.py
    build:
      context: .
      dockerfile:  ./docker/python/Dockerfile
    volumes:
      - ./tests/server.py:/server.py
    ports:
      - 8000:8000

    